spring:
  main:
    web-application-type: none

logging:
  level:
    io: INFO
    reactor: INFO
    org: INFO
    com:
      gamusdev: DEBUG

servletreactive:
  webflux:
    host: "http://localhost:8090"
    base_uri: "/api/v1/performance/"
    counter_limit: 100

